(setq package-enable-at-startup nil)
(setq gc-cons-threshold most-positive-fixnum)
(setq use-file-dialog nil)
(setq use-dialog-box nil)
(setq inhibit-startup-screen t)
(setq inhibit-startup-message t)
(setq inhibit-splash-screen t)
